nodeName: node1

db:
  type: postgres
  postgres:
    dsn: 'postgres://postgres:my-secret@paladin-postgres:5432/paladin_demo?sslmode=disable'
    autoMigrate: true
    migrationsDir: '/app/db/migrations/postgres'

rpcServer:
  http:
    port: 8548
    address: 0.0.0.0
    defaultRequestTimeout: 10m
  ws:
    port: 8549
    address: 0.0.0.0

blockIndexer:
  fromBlock: latest

blockchain:
  http:
    url: http://besu_free:8545
  ws:
    url: ws://besu_free:8546
    initialConnectAttempts: 25

log:
  level: info

wallets:
  - name: wallet1
    keySelector: .*
    signer:
      keyDerivation:
        type: 'bip32'
      keyStore:
        type: 'static'
        static:
          keys:
            seed:
              encoding: hex
              inline: f970af3738d945e28b2caf245231b12ddfbf0aaa1ee276185f682a0d54924572
