// Copyright © 2026 Kaleido, Inc.
//
// SPDX-License-Identifier: Apache-2.0

//! Build script embedding SZeto's Groth16 verification key at compile time - mirrors
//! `NethermindEth/stellar-private-payments`'s `circom-groth16-verifier/build.rs` pattern
//! (Apache-2.0), except reading directly from this repo's own `domains/zeto/zkp/
//! anon_nullifier_transfer-vkey.json` rather than an env-var path, since this phase targets
//! exactly one fixed, known circuit (see the chapter 13 plan's M0/SZeto design notes for why -
//! batch circuits and a multi-circuit VK table are out of scope for this phase).
//!
//! No persistent storage or admin mutation for the VK at all - it is part of the contract Wasm
//! itself, same rationale as the reference.

use num_bigint::BigUint;
use serde_json::Value;
use std::{env, fmt::Write as _, fs, path::PathBuf};

fn parse_fq_decimal(value: &str) -> [u8; 32] {
    let n = BigUint::parse_bytes(value.as_bytes(), 10)
        .unwrap_or_else(|| panic!("invalid decimal field element: {value}"));
    let be = n.to_bytes_be();
    assert!(be.len() <= 32, "field element too large: {value}");
    let mut out = [0u8; 32];
    out[32 - be.len()..].copy_from_slice(&be);
    out
}

/// snarkjs G1 point `[x, y, "1"]` -> Soroban's 64-byte (x || y) big-endian layout.
fn g1_bytes(pt: &Value) -> [u8; 64] {
    let arr = pt.as_array().expect("G1 point must be a JSON array");
    let x = parse_fq_decimal(arr[0].as_str().expect("G1.x must be a string"));
    let y = parse_fq_decimal(arr[1].as_str().expect("G1.y must be a string"));
    let mut out = [0u8; 64];
    out[..32].copy_from_slice(&x);
    out[32..].copy_from_slice(&y);
    out
}

/// snarkjs G2 point `[[x_c0,x_c1],[y_c0,y_c1],["1","0"]]` -> Soroban's 128-byte layout, in
/// `c1||c0` (imaginary||real) order - the reverse of snarkjs's own `[c0, c1]` convention,
/// confirmed against soroban-sdk's `Bn254G2Affine` doc comment and empirically this session
/// (chapter 13 Phase 5 M0 spike, `soroban/spikes/m0-groth16-bench`).
fn g2_bytes(pt: &Value) -> [u8; 128] {
    let arr = pt.as_array().expect("G2 point must be a JSON array");
    let x = arr[0].as_array().expect("G2.x must be a JSON array");
    let y = arr[1].as_array().expect("G2.y must be a JSON array");
    let x_c0 = parse_fq_decimal(x[0].as_str().expect("G2.x.c0 must be a string"));
    let x_c1 = parse_fq_decimal(x[1].as_str().expect("G2.x.c1 must be a string"));
    let y_c0 = parse_fq_decimal(y[0].as_str().expect("G2.y.c0 must be a string"));
    let y_c1 = parse_fq_decimal(y[1].as_str().expect("G2.y.c1 must be a string"));
    let mut out = [0u8; 128];
    out[0..32].copy_from_slice(&x_c1);
    out[32..64].copy_from_slice(&x_c0);
    out[64..96].copy_from_slice(&y_c1);
    out[96..128].copy_from_slice(&y_c0);
    out
}

fn fmt_bytes(bytes: &[u8]) -> String {
    let mut s = String::from("[");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push(',');
        }
        write!(s, "0x{b:02x}").expect("infallible write to String");
    }
    s.push(']');
    s
}

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let vk_path = manifest_dir
        .join("..")
        .join("..")
        .join("..")
        .join("domains")
        .join("zeto")
        .join("zkp")
        .join("anon_nullifier_transfer-vkey.json");
    println!("cargo:rerun-if-changed={}", vk_path.display());

    let json = fs::read_to_string(&vk_path)
        .unwrap_or_else(|e| panic!("failed to read VK file `{}`: {e}", vk_path.display()));
    let v: Value = serde_json::from_str(&json).expect("VK file is not valid JSON");

    let alpha = g1_bytes(&v["vk_alpha_1"]);
    let beta = g2_bytes(&v["vk_beta_2"]);
    let gamma = g2_bytes(&v["vk_gamma_2"]);
    let delta = g2_bytes(&v["vk_delta_2"]);

    let ic_arr = v["IC"].as_array().expect("IC must be a JSON array");
    let ic_len = ic_arr.len();
    let ic_items: Vec<String> = ic_arr.iter().map(|pt| fmt_bytes(&g1_bytes(pt))).collect();

    let mut out = String::new();
    writeln!(out, "// Auto-generated by build.rs from anon_nullifier_transfer-vkey.json - do not edit manually.").unwrap();
    writeln!(out, "const VK_ALPHA_G1: [u8; 64] = {};", fmt_bytes(&alpha)).unwrap();
    writeln!(out, "const VK_BETA_G2: [u8; 128] = {};", fmt_bytes(&beta)).unwrap();
    writeln!(out, "const VK_GAMMA_G2: [u8; 128] = {};", fmt_bytes(&gamma)).unwrap();
    writeln!(out, "const VK_DELTA_G2: [u8; 128] = {};", fmt_bytes(&delta)).unwrap();
    writeln!(
        out,
        "const VK_IC: [[u8; 64]; {ic_len}] = [{}];",
        ic_items.join(",")
    )
    .unwrap();

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    fs::write(out_dir.join("vk.rs"), out).expect("failed to write vk.rs");
}
