[package]
name = "sente"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
saladin-typed-data = { workspace = true }
atom-operation = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils", "alloc"] }
snoto = { path = "../snoto" }
ed25519-dalek = { version = "2.2.0", default-features = false, features = ["rand_core"] }
