// Copyright © 2026 Kaleido, Inc.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! SZeto (chapter 13 §13.3) - the ZK token. Supports both the non-batch `anon_nullifier_transfer`
//! circuit (2 inputs/2 outputs) and the batch `anon_nullifier_transfer_batch` circuit (10
//! inputs/10 outputs, EVM parity - chapter 13 Part B phase B.3), selected automatically per call
//! based on how many real values are passed (see `NONBATCH_SLOTS`/`BATCH_SLOTS`). Gated by the
//! chapter 13 Phase 5 M0 feasibility spike (`soroban/spikes/m0-groth16-bench`, see the chapter 13
//! plan) - both the BN254 Groth16 verifier and the on-chain Poseidon-based Merkle tree in
//! `tree.rs` are confirmed working against real, unmodified Zeto artifacts before landing here.
//!
//! **Deliberate design decisions, cross-checked against the real, vendored EVM Zeto contracts**
//! (`solidity/node_modules/@lfdecentralizedtrust/zeto-contracts/contracts/zeto_anon_nullifier.sol`,
//! `.../lib/zeto_nullifier.sol`, `@iden3/contracts/contracts/lib/SmtLib.sol`), not settled book
//! text:
//! - **Full on-chain Merkle tree maintenance, not a "trust the caller's root" shortcut.** The
//!   `anon_nullifier_transfer` circuit's public inputs contain only the *old* root (proving
//!   nullifier/input membership) - it makes no claim about output insertion, so nothing but the
//!   contract's own on-chain computation can be trusted to produce valid new roots. Skipping this
//!   (as an earlier design pass here assumed) would let a caller fabricate an arbitrary root and
//!   forge ownership of UTXOs that were never created. Confirmed real cost this session: ~94M CPU
//!   instructions per output commitment inserted in the worst case (deep tree, `MAX_SMT_DEPTH=64`
//!   levels); much cheaper early in a domain instance's life since `tree.rs` is a lazy sparse
//!   tree, not a fixed-depth walk. See `saladin-book/part-2-saladin/16-risk-map.md` R2/R3.
//! - **Compile-time embedded VKs, not runtime-configurable.** `build.rs` reads both real
//!   `domains/zeto/zkp/anon_nullifier_transfer{,_batch}-vkey.json` files at build time - exactly
//!   these two fixed circuits, so there is no general multi-circuit table (yet; `deposit`/
//!   `withdraw` circuits would need their own future extension).
//! - **1 to `BATCH_SLOTS` (10) real nullifiers/outputs per call, zero-padded by the contract, not
//!   the caller** - matches EVM's `checkAndPadCommitments` exactly (its own `enables` signals let
//!   the circuit tell padding apart from real values): the caller sends only its real values, and
//!   the contract pads to whichever of `NONBATCH_SLOTS`/`BATCH_SLOTS` fits, mirroring EVM's own
//!   regular-vs-batch verifier selection in `verifyProof`. See `BATCH_SLOTS`'s doc comment for a
//!   real, measured resource-cost caveat on batch sizes above ~5-6 today.
#![no_std]

extern crate alloc;

mod storage;
mod tree;

use soroban_sdk::{
    contract, contracterror, contractevent, contractimpl, contracttype,
    crypto::bn254::{Bn254Fr, Bn254G1Affine as G1Affine, Bn254G2Affine as G2Affine},
    token, vec, Address, Bytes, BytesN, Env, MuxedAddress, U256,
};

// Compile-time VK constants generated by build.rs from anon_nullifier_transfer-vkey.json.
include!(concat!(env!("OUT_DIR"), "/vk.rs"));

/// Non-batch slot count, matching the embedded `_N2` VK's fixed `nPublic: 7` shape
/// (nullifiers×2 + root + enables×2 + outputs×2). `transfer` uses this shape whenever both
/// `nullifiers`/`outputs` fit in 2 real (non-padding) slots - mirrors EVM's own
/// `checkAndPadCommitments`, which pads to 2 rather than `MAX_BATCH` under the same condition.
pub const NONBATCH_SLOTS: u32 = 2;
/// Batch slot count, matching the embedded `_N10` VK's fixed `nPublic: 31` shape and EVM Zeto's
/// own `MAX_BATCH` (vendored `izeto.sol`). `transfer` uses this shape whenever more than
/// `NONBATCH_SLOTS` real values are passed for either `nullifiers` or `outputs`.
///
/// ⚠️ Real, measured on-chain tree-maintenance cost (`soroban/spikes/m0-groth16-bench/
/// BENCHMARK.md`, phases M1/M1b) puts the *actually safe* worst-case batch size at N=5-6 today,
/// not N=10 - a transfer using close to `BATCH_SLOTS` real outputs may exceed Soroban's real
/// per-transaction resource ceiling even though this constant matches EVM parity. `BATCH_SLOTS`
/// itself stays at 10 because it's the embedded `_N10` VK's fixed circuit shape, not a tunable
/// parameter - `MAX_SAFE_BATCH_OUTPUTS` (below) is the actual contract-level cap enforced in
/// `transfer`, set to the measured-safe value; raise it only after re-benchmarking.
pub const BATCH_SLOTS: u32 = 10;
/// Measured-safe worst-case batch size for real (non-padding) `outputs` per `transfer()` call,
/// per the M1/M1b spike (`soroban/spikes/m0-groth16-bench/BENCHMARK.md`): N=5 real outputs holds
/// 22.0% worst-case headroom; N=6 is only marginally safe (4.7%); N=10 (`BATCH_SLOTS`) is over
/// budget (-73.8% worst-case). This bounds `outputs` specifically because the M1/M1b benchmark
/// measured `tree::insert_leaf` cost, which only real (non-zero) outputs trigger - nullifier
/// spends are flat storage writes and aren't the resource driver this cap protects against.
pub const MAX_SAFE_BATCH_OUTPUTS: u32 = 5;
/// `nPublic` for the non-batch circuit: nullifiers(`NONBATCH_SLOTS`) + root(1) +
/// enables(`NONBATCH_SLOTS`) + outputs(`NONBATCH_SLOTS`).
const NONBATCH_NPUBLIC: u32 = 3 * NONBATCH_SLOTS + 1;
/// `nPublic` for the batch circuit: nullifiers(`BATCH_SLOTS`) + root(1) + enables(`BATCH_SLOTS`)
/// + outputs(`BATCH_SLOTS`).
const BATCH_NPUBLIC: u32 = 3 * BATCH_SLOTS + 1;
/// `nPublic` for the `deposit` circuit: amount(1) + outputs(2) - always exactly 2 outputs, not
/// zero-padded/variable like `transfer` (confirmed against the vendored `_deposit`/
/// `constructPublicInputs`-adjacent code in `zeto_fungible.sol`, which indexes `outputs[0]`/
/// `outputs[1]` unconditionally).
const DEPOSIT_NPUBLIC: u32 = 3;
/// `nPublic` for the non-batch `withdraw_nullifier` circuit: amount(1), nullifiers(2), root(1),
/// enables(2), output(1). Numerically equal to `NONBATCH_NPUBLIC` (7) despite being a completely
/// different trusted setup/public-input meaning - see `verify_with_vk`'s doc comment for why
/// this means `nPublic` alone can't select a VK for every circuit in this contract.
const WITHDRAW_NPUBLIC: u32 = 7;

/// Selects which embedded verification key a proof is checked against - each of this contract's
/// circuits (`anon_nullifier_transfer`, `anon_nullifier_transfer_batch`, `deposit`,
/// `withdraw_nullifier`) is a separate trusted setup, not one parameterized circuit, so there is
/// no single VK that fits more than one shape.
#[derive(Clone, Copy)]
enum CircuitSize {
    NonBatch,
    Batch,
    Deposit,
    Withdraw,
}

/// Errors that can occur during Groth16 proof verification. Ported from the reference verifier
/// (`NethermindEth/stellar-private-payments`, Apache-2.0) - see `soroban/spikes/
/// m0-groth16-bench` for the M0 spike that validated this design against a real Zeto proof.
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Groth16Error {
    InvalidProof = 0,
    MalformedPublicInputs = 1,
}

#[derive(Clone)]
struct VerificationKey {
    alpha: G1Affine,
    beta: G2Affine,
    gamma: G2Affine,
    delta: G2Affine,
    ic: soroban_sdk::Vec<G1Affine>,
}

/// Groth16 proof composed of points A, B, and C. `b` (G2) uses Soroban's `c1||c0`
/// (imaginary||real) ordering - see `sdk/go/pkg/groth16bn254` for the Go-side conversion from
/// Zeto's snarkjs-decimal proof output into this shape.
#[contracttype]
#[derive(Clone)]
pub struct Groth16Proof {
    pub a: G1Affine,
    pub b: G2Affine,
    pub c: G1Affine,
}

fn embedded_vk(env: &Env, size: CircuitSize) -> VerificationKey {
    let mut ic_vec: soroban_sdk::Vec<G1Affine> = soroban_sdk::Vec::new(env);
    let (alpha, beta, gamma, delta): (&[u8; 64], &[u8; 128], &[u8; 128], &[u8; 128]) = match size {
        CircuitSize::NonBatch => {
            for bytes in VK_IC_N2.iter() {
                ic_vec.push_back(G1Affine::from_bytes(BytesN::from_array(env, bytes)));
            }
            (
                &VK_ALPHA_G1_N2,
                &VK_BETA_G2_N2,
                &VK_GAMMA_G2_N2,
                &VK_DELTA_G2_N2,
            )
        }
        CircuitSize::Batch => {
            for bytes in VK_IC_N10.iter() {
                ic_vec.push_back(G1Affine::from_bytes(BytesN::from_array(env, bytes)));
            }
            (
                &VK_ALPHA_G1_N10,
                &VK_BETA_G2_N10,
                &VK_GAMMA_G2_N10,
                &VK_DELTA_G2_N10,
            )
        }
        CircuitSize::Deposit => {
            for bytes in VK_IC_DEPOSIT.iter() {
                ic_vec.push_back(G1Affine::from_bytes(BytesN::from_array(env, bytes)));
            }
            (
                &VK_ALPHA_G1_DEPOSIT,
                &VK_BETA_G2_DEPOSIT,
                &VK_GAMMA_G2_DEPOSIT,
                &VK_DELTA_G2_DEPOSIT,
            )
        }
        CircuitSize::Withdraw => {
            for bytes in VK_IC_WITHDRAW.iter() {
                ic_vec.push_back(G1Affine::from_bytes(BytesN::from_array(env, bytes)));
            }
            (
                &VK_ALPHA_G1_WITHDRAW,
                &VK_BETA_G2_WITHDRAW,
                &VK_GAMMA_G2_WITHDRAW,
                &VK_DELTA_G2_WITHDRAW,
            )
        }
    };
    VerificationKey {
        alpha: G1Affine::from_bytes(BytesN::from_array(env, alpha)),
        beta: G2Affine::from_bytes(BytesN::from_array(env, beta)),
        gamma: G2Affine::from_bytes(BytesN::from_array(env, gamma)),
        delta: G2Affine::from_bytes(BytesN::from_array(env, delta)),
        ic: ic_vec,
    }
}

/// Verify a Groth16 proof against an already-selected verification key. Ported essentially
/// unchanged from the reference's `verify_with_vk`: accumulate `vk_x = ic[0] +
/// sum(public_input[i] * ic[i+1])`, then check `e(-A,B) * e(alpha,beta) * e(vk_x,gamma) *
/// e(C,delta) == 1`. Size-agnostic on purpose - `nPublic` alone cannot disambiguate all of this
/// contract's circuits (the withdraw circuit happens to share `nPublic: 7` with the non-batch
/// transfer circuit, despite being a completely different trusted setup with a different public-
/// input meaning), so callers select the VK themselves rather than this function inferring it.
fn verify_with_vk(
    env: &Env,
    vk: &VerificationKey,
    proof: Groth16Proof,
    pub_inputs: soroban_sdk::Vec<Bn254Fr>,
) -> Result<bool, Groth16Error> {
    let bn = env.crypto().bn254();

    if pub_inputs.len().checked_add(1) != Some(vk.ic.len()) {
        return Err(Groth16Error::MalformedPublicInputs);
    }

    let mut vk_x = vk.ic.get(0).ok_or(Groth16Error::MalformedPublicInputs)?;
    for i in 0..pub_inputs.len() {
        let s = pub_inputs
            .get(i)
            .ok_or(Groth16Error::MalformedPublicInputs)?;
        let ic_idx = i
            .checked_add(1)
            .ok_or(Groth16Error::MalformedPublicInputs)?;
        let v = vk
            .ic
            .get(ic_idx)
            .ok_or(Groth16Error::MalformedPublicInputs)?;
        let prod = bn.g1_mul(&v, &s);
        vk_x = bn.g1_add(&vk_x, &prod);
    }

    #[allow(clippy::arithmetic_side_effects)]
    let neg_a = -proof.a;

    let g1_points = vec![env, neg_a, vk.alpha.clone(), vk_x, proof.c];
    let g2_points = vec![
        env,
        proof.b,
        vk.beta.clone(),
        vk.gamma.clone(),
        vk.delta.clone(),
    ];

    if bn.pairing_check(g1_points, g2_points) {
        Ok(true)
    } else {
        Err(Groth16Error::InvalidProof)
    }
}

/// Verify a Groth16 proof against the embedded verification key matching `pub_inputs`' length -
/// `NONBATCH_NPUBLIC` (7) selects the non-batch transfer VK, `BATCH_NPUBLIC` (31) selects the
/// batch transfer VK. Used only by `transfer`/the public `verify` entrypoint - `deposit`/
/// `withdraw` select their own VK directly via `verify_with_vk`, since their `nPublic`s are not
/// uniquely distinguishing (see `verify_with_vk`'s doc comment).
fn verify_proof(
    env: &Env,
    proof: Groth16Proof,
    pub_inputs: soroban_sdk::Vec<Bn254Fr>,
) -> Result<bool, Groth16Error> {
    let size = match pub_inputs.len() {
        NONBATCH_NPUBLIC => CircuitSize::NonBatch,
        BATCH_NPUBLIC => CircuitSize::Batch,
        _ => return Err(Groth16Error::MalformedPublicInputs),
    };
    let vk = embedded_vk(env, size);
    verify_with_vk(env, &vk, proof, pub_inputs)
}

#[contractevent(topics = ["transfer"], data_format = "vec")]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Transfer {
    #[topic]
    pub tx_id: BytesN<32>,
    pub nullifiers: soroban_sdk::Vec<BytesN<32>>,
    pub outputs: soroban_sdk::Vec<BytesN<32>>,
    pub data: Bytes,
}

/// Shield disclosure profile matches EVM Zeto's own `deposit` exactly: amount and depositor are
/// public, only the output values/ownership are private (book §13.6).
#[contractevent(topics = ["deposit"], data_format = "vec")]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Deposit {
    #[topic]
    pub from: Address,
    pub amount: i128,
    pub outputs: soroban_sdk::Vec<BytesN<32>>,
    pub data: Bytes,
}

/// Unshield disclosure profile: amount and recipient are public, matching EVM's `_erc20.transfer
/// (msg.sender, amount)` at the end of `withdraw`.
#[contractevent(topics = ["withdraw"], data_format = "vec")]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Withdraw {
    #[topic]
    pub recipient: Address,
    pub amount: i128,
    pub nullifiers: soroban_sdk::Vec<BytesN<32>>,
    pub output: BytesN<32>,
    pub data: Bytes,
}

fn bytes32_to_u256(env: &Env, b: &BytesN<32>) -> U256 {
    U256::from_be_bytes(env, &Bytes::from_array(env, &b.to_array()))
}

fn bytes32_to_bn254fr(b: &BytesN<32>) -> Bn254Fr {
    Bn254Fr::from_bytes(b.clone())
}

fn is_zero(env: &Env, b: &BytesN<32>) -> bool {
    *b == BytesN::from_array(env, &[0u8; 32])
}

/// Zero-pads `values` up to `slots` elements - matches EVM's own `checkAndPadCommitments`
/// convention: the caller sends only its real (non-padding) values, the contract pads.
fn pad_to(
    env: &Env,
    values: &soroban_sdk::Vec<BytesN<32>>,
    slots: u32,
) -> soroban_sdk::Vec<BytesN<32>> {
    let mut out: soroban_sdk::Vec<BytesN<32>> = soroban_sdk::Vec::new(env);
    for v in values.iter() {
        out.push_back(v);
    }
    while out.len() < slots {
        out.push_back(BytesN::from_array(env, &[0u8; 32]));
    }
    out
}

#[contract]
pub struct Contract;

#[contractimpl]
impl Contract {
    pub fn initialize(env: Env, notary: Address, sac: Address) {
        if storage::has_notary(&env) {
            panic!("szeto: already initialized");
        }
        storage::init_notary(&env, &notary);
        storage::init_sac(&env, &sac);
    }

    /// Verify a Groth16 proof against the embedded `anon_nullifier_transfer` verification key -
    /// exposed for testing/tooling; `transfer` calls this internally too.
    pub fn verify(
        env: Env,
        proof: Groth16Proof,
        public_inputs: soroban_sdk::Vec<Bn254Fr>,
    ) -> Result<bool, Groth16Error> {
        verify_proof(&env, proof, public_inputs)
    }

    pub fn get_root(env: Env) -> U256 {
        tree::get_root(&env)
    }

    pub fn root_exists(env: Env, root: U256) -> bool {
        tree::root_exists(&env, &root)
    }

    /// Transfers value between UTXOs, exactly like `Zeto_AnonNullifier.transfer`
    /// (`solidity/node_modules/@lfdecentralizedtrust/zeto-contracts/contracts/
    /// zeto_anon_nullifier.sol`): notary-authorized, verifies a Groth16 proof of valid spend, then
    /// spends the nullifiers and inserts the new output commitments into the on-chain tree.
    ///
    /// `nullifiers`/`outputs` are the caller's *real* (non-padding) values - 1 to `BATCH_SLOTS`
    /// (10) nullifiers, 1 to `MAX_SAFE_BATCH_OUTPUTS` (5) outputs (the contract's own enforced,
    /// measured-safe cap - see its doc comment). The contract zero-pads up to `NONBATCH_SLOTS`
    /// (2) or `BATCH_SLOTS` (10), whichever fits, and picks the matching embedded VK - matches
    /// EVM's own `checkAndPadCommitments`/`verifyProof` regular-vs-batch selection exactly
    /// (chapter 13 Part B, phase B.3).
    pub fn transfer(
        env: Env,
        tx_id: BytesN<32>,
        nullifiers: soroban_sdk::Vec<BytesN<32>>,
        outputs: soroban_sdk::Vec<BytesN<32>>,
        root: BytesN<32>,
        proof: Groth16Proof,
        data: Bytes,
    ) {
        if nullifiers.len() > BATCH_SLOTS || outputs.len() > BATCH_SLOTS {
            panic!("szeto: transfer supports at most 10 nullifiers and 10 outputs");
        }
        if outputs.len() > MAX_SAFE_BATCH_OUTPUTS {
            panic!("szeto: transfer supports at most 5 real outputs (measured safe batch size — see BENCHMARK.md)");
        }
        let slots = if nullifiers.len() > NONBATCH_SLOTS || outputs.len() > NONBATCH_SLOTS {
            BATCH_SLOTS
        } else {
            NONBATCH_SLOTS
        };
        let nullifiers = pad_to(&env, &nullifiers, slots);
        let outputs = pad_to(&env, &outputs, slots);

        storage::notary(&env).require_auth();
        storage::mark_tx_used(&env, &tx_id);

        let root_u256 = bytes32_to_u256(&env, &root);
        if !tree::root_exists(&env, &root_u256) {
            panic!("szeto: unknown root");
        }

        for n in nullifiers.iter() {
            if !is_zero(&env, &n) && storage::is_spent(&env, &n) {
                panic!("szeto: nullifier already spent");
            }
        }

        // Public input order matches `constructPublicInputs` (non-locked): nullifiers[0..slots],
        // root, enables[0..slots] (1 if nullifier != 0 else 0), outputs[0..slots].
        let mut public_inputs: soroban_sdk::Vec<Bn254Fr> = soroban_sdk::Vec::new(&env);
        for n in nullifiers.iter() {
            public_inputs.push_back(bytes32_to_bn254fr(&n));
        }
        public_inputs.push_back(bytes32_to_bn254fr(&root));
        for n in nullifiers.iter() {
            let enable = if is_zero(&env, &n) { 0u32 } else { 1u32 };
            public_inputs.push_back(Bn254Fr::from_u256(U256::from_u32(&env, enable)));
        }
        for o in outputs.iter() {
            public_inputs.push_back(bytes32_to_bn254fr(&o));
        }

        match verify_proof(&env, proof, public_inputs) {
            Ok(true) => {}
            _ => panic!("szeto: invalid proof"),
        }

        for n in nullifiers.iter() {
            if !is_zero(&env, &n) {
                storage::mark_spent(&env, &n);
            }
        }
        for o in outputs.iter() {
            if !is_zero(&env, &o) {
                let value = bytes32_to_u256(&env, &o);
                tree::insert_leaf(&env, value.clone(), value);
            }
        }

        Transfer {
            tx_id,
            nullifiers,
            outputs,
            data,
        }
        .publish(&env);
    }

    /// Shields (deposits) `amount` of the pooled SAC asset into two new private UTXOs - book
    /// §13.6. `from` authorizes the real SAC transfer itself (a genuine Soroban auth entry with
    /// its own native replay protection), so unlike `transfer`/`withdraw` this needs no separate
    /// `tx_id` replay guard. `outputs` must have exactly 2 elements - the `deposit` circuit's own
    /// fixed shape (confirmed against `zeto_fungible.sol`'s `_deposit`, which indexes
    /// `outputs[0]`/`outputs[1]` unconditionally, not zero-padded/variable like `transfer`).
    pub fn deposit(
        env: Env,
        from: Address,
        amount: i128,
        outputs: soroban_sdk::Vec<BytesN<32>>,
        proof: Groth16Proof,
        data: Bytes,
    ) {
        from.require_auth();
        if amount <= 0 {
            panic!("szeto: deposit amount must be positive");
        }
        if outputs.len() != DEPOSIT_NPUBLIC - 1 {
            panic!("szeto: deposit requires exactly 2 outputs");
        }

        let mut public_inputs: soroban_sdk::Vec<Bn254Fr> = soroban_sdk::Vec::new(&env);
        public_inputs.push_back(Bn254Fr::from_u256(U256::from_u128(&env, amount as u128)));
        for o in outputs.iter() {
            public_inputs.push_back(bytes32_to_bn254fr(&o));
        }
        assert_eq!(public_inputs.len(), DEPOSIT_NPUBLIC);

        let vk = embedded_vk(&env, CircuitSize::Deposit);
        match verify_with_vk(&env, &vk, proof, public_inputs) {
            Ok(true) => {}
            _ => panic!("szeto: invalid proof"),
        }

        let sac = storage::sac(&env);
        token::TokenClient::new(&env, &sac).transfer(
            &from,
            MuxedAddress::from(env.current_contract_address()),
            &amount,
        );

        for o in outputs.iter() {
            let value = bytes32_to_u256(&env, &o);
            tree::insert_leaf(&env, value.clone(), value);
        }

        Deposit {
            from,
            amount,
            outputs,
            data,
        }
        .publish(&env);
    }

    /// Unshields (withdraws) `amount` of the pooled SAC asset to `recipient`, spending up to 2
    /// nullifiers and admitting one change `output` - book §13.6. Notary-authorized and `tx_id`-
    /// replay-guarded like `transfer` (unlike `deposit`, there is no separately-authorizing real
    /// party here - the notary alone drives this, submitted via an anonymous channel account per
    /// chapter 12's model, so it needs the same explicit replay guard `transfer` has). Batch
    /// withdraw (`withdraw_nullifier_batch`) is out of scope for this phase.
    #[allow(clippy::too_many_arguments)]
    pub fn withdraw(
        env: Env,
        tx_id: BytesN<32>,
        recipient: Address,
        amount: i128,
        nullifiers: soroban_sdk::Vec<BytesN<32>>,
        output: BytesN<32>,
        root: BytesN<32>,
        proof: Groth16Proof,
        data: Bytes,
    ) {
        if amount <= 0 {
            panic!("szeto: withdraw amount must be positive");
        }
        if nullifiers.len() > NONBATCH_SLOTS {
            panic!("szeto: withdraw supports at most 2 nullifiers");
        }
        let nullifiers = pad_to(&env, &nullifiers, NONBATCH_SLOTS);

        storage::notary(&env).require_auth();
        storage::mark_tx_used(&env, &tx_id);

        let root_u256 = bytes32_to_u256(&env, &root);
        if !tree::root_exists(&env, &root_u256) {
            panic!("szeto: unknown root");
        }
        for n in nullifiers.iter() {
            if !is_zero(&env, &n) && storage::is_spent(&env, &n) {
                panic!("szeto: nullifier already spent");
            }
        }

        // Public input order matches the vendored `withdraw_nullifier` circuit's own
        // constructPublicInputs-adjacent code: amount, nullifiers[0..2], root, enables[0..2],
        // output.
        let mut public_inputs: soroban_sdk::Vec<Bn254Fr> = soroban_sdk::Vec::new(&env);
        public_inputs.push_back(Bn254Fr::from_u256(U256::from_u128(&env, amount as u128)));
        for n in nullifiers.iter() {
            public_inputs.push_back(bytes32_to_bn254fr(&n));
        }
        public_inputs.push_back(bytes32_to_bn254fr(&root));
        for n in nullifiers.iter() {
            let enable = if is_zero(&env, &n) { 0u32 } else { 1u32 };
            public_inputs.push_back(Bn254Fr::from_u256(U256::from_u32(&env, enable)));
        }
        public_inputs.push_back(bytes32_to_bn254fr(&output));
        assert_eq!(public_inputs.len(), WITHDRAW_NPUBLIC);

        let vk = embedded_vk(&env, CircuitSize::Withdraw);
        match verify_with_vk(&env, &vk, proof, public_inputs) {
            Ok(true) => {}
            _ => panic!("szeto: invalid proof"),
        }

        for n in nullifiers.iter() {
            if !is_zero(&env, &n) {
                storage::mark_spent(&env, &n);
            }
        }
        if !is_zero(&env, &output) {
            let value = bytes32_to_u256(&env, &output);
            tree::insert_leaf(&env, value.clone(), value);
        }

        let sac = storage::sac(&env);
        token::TokenClient::new(&env, &sac).transfer(
            &env.current_contract_address(),
            MuxedAddress::from(recipient.clone()),
            &amount,
        );

        Withdraw {
            recipient,
            amount,
            nullifiers,
            output,
            data,
        }
        .publish(&env);
    }
}

#[cfg(test)]
mod test;

#[cfg(test)]
mod real_transfer_test;

#[cfg(test)]
mod batch_bench_test;
