// Copyright © 2026 Kaleido, Inc.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! SZeto (chapter 13 §13.3) - the ZK token, scoped this phase to the non-batch
//! `anon_nullifier_transfer` circuit only (max 2 inputs/2 outputs per transfer). Gated by the
//! chapter 13 Phase 5 M0 feasibility spike (`soroban/spikes/m0-groth16-bench`, see the chapter 13
//! plan) - both the BN254 Groth16 verifier and the on-chain Poseidon-based Merkle tree in
//! `tree.rs` are confirmed working against real, unmodified Zeto artifacts before landing here.
//!
//! **Deliberate design decisions, cross-checked against the real, vendored EVM Zeto contracts**
//! (`solidity/node_modules/@lfdecentralizedtrust/zeto-contracts/contracts/zeto_anon_nullifier.sol`,
//! `.../lib/zeto_nullifier.sol`, `@iden3/contracts/contracts/lib/SmtLib.sol`), not settled book
//! text:
//! - **Full on-chain Merkle tree maintenance, not a "trust the caller's root" shortcut.** The
//!   `anon_nullifier_transfer` circuit's public inputs contain only the *old* root (proving
//!   nullifier/input membership) - it makes no claim about output insertion, so nothing but the
//!   contract's own on-chain computation can be trusted to produce valid new roots. Skipping this
//!   (as an earlier design pass here assumed) would let a caller fabricate an arbitrary root and
//!   forge ownership of UTXOs that were never created. Confirmed real cost this session: ~94M CPU
//!   instructions per output commitment inserted in the worst case (deep tree, `MAX_SMT_DEPTH=64`
//!   levels); much cheaper early in a domain instance's life since `tree.rs` is a lazy sparse
//!   tree, not a fixed-depth walk. See `saladin-book/part-2-saladin/16-risk-map.md` R2/R3.
//! - **Compile-time embedded VK, not runtime-configurable.** `build.rs` reads the real
//!   `domains/zeto/zkp/anon_nullifier_transfer-vkey.json` at build time - this phase targets
//!   exactly one fixed circuit, so there is no multi-circuit table (yet).
//! - **Exactly 2 nullifiers / 2 outputs per call, zero-padded by the caller for fewer real
//!   values** - matches EVM's `checkAndPadCommitments` exactly (its own `enables` signals let the
//!   circuit tell padding apart from real values), and matches the embedded VK's fixed
//!   `nPublic: 7` shape (nullifiers×2 + root + enables×2 + outputs×2).
#![no_std]

extern crate alloc;

mod storage;
mod tree;

use soroban_sdk::{
    contract, contracterror, contractevent, contractimpl, contracttype,
    crypto::bn254::{Bn254Fr, Bn254G1Affine as G1Affine, Bn254G2Affine as G2Affine},
    vec, Address, Bytes, BytesN, Env, U256,
};

// Compile-time VK constants generated by build.rs from anon_nullifier_transfer-vkey.json.
include!(concat!(env!("OUT_DIR"), "/vk.rs"));

/// Fixed input/output count for `transfer`, matching the embedded VK's fixed `nPublic: 7` shape
/// (nullifiers×2 + root + enables×2 + outputs×2) - not a tunable batch-size parameter. Derived
/// from measured on-chain tree-maintenance cost (`soroban/spikes/m0-groth16-bench/BENCHMARK.md`):
/// each output insert costs up to ~93.6M CPU instructions worst-case (`MAX_SMT_DEPTH` Poseidon
/// calls), so a 2-output transfer already uses ~216M of the 600M mainnet instruction budget.
/// EVM Zeto's batch circuit supports 10 inputs/outputs (`MAX_BATCH` in the vendored
/// `izeto.sol`); matching that under full on-chain tree maintenance is not feasible in the
/// worst case (~936M instructions) and is scoped to a separate future phase.
pub const MAX_INPUTS: u32 = 2;
pub const MAX_OUTPUTS: u32 = 2;

/// Errors that can occur during Groth16 proof verification. Ported from the reference verifier
/// (`NethermindEth/stellar-private-payments`, Apache-2.0) - see `soroban/spikes/
/// m0-groth16-bench` for the M0 spike that validated this design against a real Zeto proof.
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Groth16Error {
    InvalidProof = 0,
    MalformedPublicInputs = 1,
}

#[derive(Clone)]
struct VerificationKey {
    alpha: G1Affine,
    beta: G2Affine,
    gamma: G2Affine,
    delta: G2Affine,
    ic: soroban_sdk::Vec<G1Affine>,
}

/// Groth16 proof composed of points A, B, and C. `b` (G2) uses Soroban's `c1||c0`
/// (imaginary||real) ordering - see `sdk/go/pkg/groth16bn254` for the Go-side conversion from
/// Zeto's snarkjs-decimal proof output into this shape.
#[contracttype]
#[derive(Clone)]
pub struct Groth16Proof {
    pub a: G1Affine,
    pub b: G2Affine,
    pub c: G1Affine,
}

fn embedded_vk(env: &Env) -> VerificationKey {
    let mut ic_vec: soroban_sdk::Vec<G1Affine> = soroban_sdk::Vec::new(env);
    for bytes in VK_IC.iter() {
        ic_vec.push_back(G1Affine::from_bytes(BytesN::from_array(env, bytes)));
    }
    VerificationKey {
        alpha: G1Affine::from_bytes(BytesN::from_array(env, &VK_ALPHA_G1)),
        beta: G2Affine::from_bytes(BytesN::from_array(env, &VK_BETA_G2)),
        gamma: G2Affine::from_bytes(BytesN::from_array(env, &VK_GAMMA_G2)),
        delta: G2Affine::from_bytes(BytesN::from_array(env, &VK_DELTA_G2)),
        ic: ic_vec,
    }
}

/// Verify a Groth16 proof against the embedded verification key. Ported essentially unchanged
/// from the reference's `verify_with_vk`: accumulate `vk_x = ic[0] + sum(public_input[i] *
/// ic[i+1])`, then check `e(-A,B) * e(alpha,beta) * e(vk_x,gamma) * e(C,delta) == 1`.
fn verify_proof(
    env: &Env,
    proof: Groth16Proof,
    pub_inputs: soroban_sdk::Vec<Bn254Fr>,
) -> Result<bool, Groth16Error> {
    let vk = embedded_vk(env);
    let bn = env.crypto().bn254();

    if pub_inputs.len().checked_add(1) != Some(vk.ic.len()) {
        return Err(Groth16Error::MalformedPublicInputs);
    }

    let mut vk_x = vk.ic.get(0).ok_or(Groth16Error::MalformedPublicInputs)?;
    for i in 0..pub_inputs.len() {
        let s = pub_inputs
            .get(i)
            .ok_or(Groth16Error::MalformedPublicInputs)?;
        let ic_idx = i
            .checked_add(1)
            .ok_or(Groth16Error::MalformedPublicInputs)?;
        let v = vk
            .ic
            .get(ic_idx)
            .ok_or(Groth16Error::MalformedPublicInputs)?;
        let prod = bn.g1_mul(&v, &s);
        vk_x = bn.g1_add(&vk_x, &prod);
    }

    #[allow(clippy::arithmetic_side_effects)]
    let neg_a = -proof.a;

    let g1_points = vec![env, neg_a, vk.alpha.clone(), vk_x, proof.c];
    let g2_points = vec![
        env,
        proof.b,
        vk.beta.clone(),
        vk.gamma.clone(),
        vk.delta.clone(),
    ];

    if bn.pairing_check(g1_points, g2_points) {
        Ok(true)
    } else {
        Err(Groth16Error::InvalidProof)
    }
}

#[contractevent(topics = ["transfer"], data_format = "vec")]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Transfer {
    #[topic]
    pub tx_id: BytesN<32>,
    pub nullifiers: soroban_sdk::Vec<BytesN<32>>,
    pub outputs: soroban_sdk::Vec<BytesN<32>>,
    pub data: Bytes,
}

fn bytes32_to_u256(env: &Env, b: &BytesN<32>) -> U256 {
    U256::from_be_bytes(env, &Bytes::from_array(env, &b.to_array()))
}

fn bytes32_to_bn254fr(b: &BytesN<32>) -> Bn254Fr {
    Bn254Fr::from_bytes(b.clone())
}

fn is_zero(env: &Env, b: &BytesN<32>) -> bool {
    *b == BytesN::from_array(env, &[0u8; 32])
}

#[contract]
pub struct Contract;

#[contractimpl]
impl Contract {
    pub fn initialize(env: Env, notary: Address) {
        if storage::has_notary(&env) {
            panic!("szeto: already initialized");
        }
        storage::init_notary(&env, &notary);
    }

    /// Verify a Groth16 proof against the embedded `anon_nullifier_transfer` verification key -
    /// exposed for testing/tooling; `transfer` calls this internally too.
    pub fn verify(
        env: Env,
        proof: Groth16Proof,
        public_inputs: soroban_sdk::Vec<Bn254Fr>,
    ) -> Result<bool, Groth16Error> {
        verify_proof(&env, proof, public_inputs)
    }

    pub fn get_root(env: Env) -> U256 {
        tree::get_root(&env)
    }

    pub fn root_exists(env: Env, root: U256) -> bool {
        tree::root_exists(&env, &root)
    }

    /// Transfers value between UTXOs, exactly like `Zeto_AnonNullifier.transfer`
    /// (`solidity/node_modules/@lfdecentralizedtrust/zeto-contracts/contracts/
    /// zeto_anon_nullifier.sol`): notary-authorized, verifies a Groth16 proof of valid spend, then
    /// spends the nullifiers and inserts the new output commitments into the on-chain tree.
    ///
    /// `nullifiers`/`outputs` must each have exactly 2 elements - zero-pad (an all-zero
    /// `BytesN<32>`) unused slots, matching EVM's own `checkAndPadCommitments` convention exactly.
    pub fn transfer(
        env: Env,
        tx_id: BytesN<32>,
        nullifiers: soroban_sdk::Vec<BytesN<32>>,
        outputs: soroban_sdk::Vec<BytesN<32>>,
        root: BytesN<32>,
        proof: Groth16Proof,
        data: Bytes,
    ) {
        if nullifiers.len() != MAX_INPUTS || outputs.len() != MAX_OUTPUTS {
            panic!("szeto: transfer requires exactly 2 nullifiers and 2 outputs (zero-pad unused slots)");
        }

        storage::notary(&env).require_auth();
        storage::mark_tx_used(&env, &tx_id);

        let root_u256 = bytes32_to_u256(&env, &root);
        if !tree::root_exists(&env, &root_u256) {
            panic!("szeto: unknown root");
        }

        for n in nullifiers.iter() {
            if !is_zero(&env, &n) && storage::is_spent(&env, &n) {
                panic!("szeto: nullifier already spent");
            }
        }

        // Public input order matches `constructPublicInputs` (non-locked, non-batch, 2-in/2-out):
        // nullifiers[0..2], root, enables[0..2] (1 if nullifier != 0 else 0), outputs[0..2].
        let mut public_inputs: soroban_sdk::Vec<Bn254Fr> = soroban_sdk::Vec::new(&env);
        for n in nullifiers.iter() {
            public_inputs.push_back(bytes32_to_bn254fr(&n));
        }
        public_inputs.push_back(bytes32_to_bn254fr(&root));
        for n in nullifiers.iter() {
            let enable = if is_zero(&env, &n) { 0u32 } else { 1u32 };
            public_inputs.push_back(Bn254Fr::from_u256(U256::from_u32(&env, enable)));
        }
        for o in outputs.iter() {
            public_inputs.push_back(bytes32_to_bn254fr(&o));
        }

        match verify_proof(&env, proof, public_inputs) {
            Ok(true) => {}
            _ => panic!("szeto: invalid proof"),
        }

        for n in nullifiers.iter() {
            if !is_zero(&env, &n) {
                storage::mark_spent(&env, &n);
            }
        }
        for o in outputs.iter() {
            if !is_zero(&env, &o) {
                let value = bytes32_to_u256(&env, &o);
                tree::insert_leaf(&env, value.clone(), value);
            }
        }

        Transfer {
            tx_id,
            nullifiers,
            outputs,
            data,
        }
        .publish(&env);
    }
}

#[cfg(test)]
mod test;

#[cfg(test)]
mod real_transfer_test;

#[cfg(test)]
mod batch_bench_test;
