// Copyright © 2026 Kaleido, Inc.
//
// SPDX-License-Identifier: Apache-2.0

//! Closes book acceptance criterion #3 ("SZeto verifies a proof generated by the existing,
//! unmodified Zeto Go prover from this repo's test fixtures") - `test.rs`'s tests only ever
//! exercise panics that fire *before* `verify_proof` is reached; this is the first test that
//! calls the real public `transfer()` entrypoint with a proof that actually verifies.
//!
//! The fixture (`fixtures/real_anon_nullifier_transfer_proof.json`,
//! `fixtures/real_anon_nullifier_transfer_seed_leaves.json`) was generated by a throwaway Go
//! harness (`domains/zeto/internal/zeto/signer/szeto_fixture_gen_test.go`) that calls Zeto's own,
//! unmodified prover code (`snark_prover.go`'s `loadCircuit`/`calculateWitness`/`generateProof`,
//! the same real, checked-in `domains/zeto/zkp/anon_nullifier_transfer_js/
//! anon_nullifier_transfer.wasm` + `.zkey` this crate's own `build.rs` reads the verification key
//! from) against a genuine, value-conserving transfer: Alice's 2 real input UTXOs (values 10 and
//! 20, real BabyJubJub keys/salts, inserted into a real `github.com/LFDT-Paladin/smt` tree to get
//! a genuine root + Merkle proofs) split into 2 real outputs for Bob (12) and Carol (18) -
//! 10 + 20 = 12 + 18 = 30. Independently verified with `snarkjs groth16 verify` against the real
//! `anon_nullifier_transfer-vkey.json` before being committed here.
//!
//! Root-seeding: the two input-UTXO commitments are inserted into `tree.rs` via
//! `tree::insert_leaf` (the only mechanism available today to seed genesis UTXOs - there is no
//! mint/deposit entrypoint yet, and insertion order doesn't affect an SMT's final root, which
//! only depends on each leaf's own index bits). This is the same idiom `test.rs` already uses to
//! seed prior state directly via `env.as_contract`. Before calling `transfer`, the test asserts
//! `tree::get_root()` matches the fixture's own claimed root - this is the concrete, executable
//! form of the B.2.1 cross-implementation parity check (`test.rs`'s
//! `tree_matches_go_lfdt_paladin_smt_implementation`): if Go's SMT (which produced this fixture's
//! root) and Rust's `tree.rs` ever disagreed, this assertion is where it would be caught, before
//! ever blaming the proof itself.

extern crate std;

use super::*;
use num_bigint::BigUint;
use serde::Deserialize;
use soroban_sdk::testutils::Address as _;
use std::{fs, path::PathBuf, string::String, vec::Vec as StdVec};

#[derive(Deserialize)]
struct ProofData {
    pi_a: StdVec<String>,
    pi_b: StdVec<StdVec<String>>,
    pi_c: StdVec<String>,
}

#[derive(Deserialize)]
struct SnarkjsProof {
    proof: ProofData,
    pub_signals: StdVec<String>,
}

#[derive(Deserialize)]
struct SeedLeaf {
    index: String,
    value: String,
}

/// Decimal field-element string -> 32-byte big-endian, matching `soroban/spikes/
/// m0-groth16-bench/src/real_zeto_fixtures.rs`'s `fe_bytes` (an independent Rust
/// re-implementation of the same conversion `sdk/go/pkg/groth16bn254` does Go-side).
fn fe_bytes(decimal: &str) -> [u8; 32] {
    let n = BigUint::parse_bytes(decimal.as_bytes(), 10).expect("invalid decimal field element");
    let be = n.to_bytes_be();
    assert!(be.len() <= 32, "field element too large");
    let mut out = [0u8; 32];
    out[32 - be.len()..].copy_from_slice(&be);
    out
}

fn g1_bytes(x: &str, y: &str) -> [u8; 64] {
    let mut out = [0u8; 64];
    out[..32].copy_from_slice(&fe_bytes(x));
    out[32..].copy_from_slice(&fe_bytes(y));
    out
}

/// Soroban orders Fp2 as c1||c0 (imaginary||real) - the reverse of snarkjs's [c0, c1].
fn g2_bytes(x_c0: &str, x_c1: &str, y_c0: &str, y_c1: &str) -> [u8; 128] {
    let mut out = [0u8; 128];
    out[0..32].copy_from_slice(&fe_bytes(x_c1));
    out[32..64].copy_from_slice(&fe_bytes(x_c0));
    out[64..96].copy_from_slice(&fe_bytes(y_c1));
    out[96..128].copy_from_slice(&fe_bytes(y_c0));
    out
}

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures")
        .join(name)
}

#[test]
fn transfer_verifies_real_anon_nullifier_transfer_proof() {
    let proof_json = fs::read_to_string(fixture_path("real_anon_nullifier_transfer_proof.json"))
        .expect("read proof fixture");
    let fixture: SnarkjsProof = serde_json::from_str(&proof_json).expect("parse proof fixture");

    let seed_json = fs::read_to_string(fixture_path(
        "real_anon_nullifier_transfer_seed_leaves.json",
    ))
    .expect("read seed leaves fixture");
    let seed_leaves: StdVec<SeedLeaf> =
        serde_json::from_str(&seed_json).expect("parse seed leaves fixture");

    let env = Env::default();
    env.mock_all_auths();
    let contract_id = env.register(Contract, ());
    let notary = Address::generate(&env);
    let client = ContractClient::new(&env, &contract_id);
    client.initialize(&notary);

    // Public-input order matches `constructPublicInputs`/lib.rs's own `transfer` assembly
    // exactly: nullifiers[0..2], root, enables[0..2], outputs[0..2] (nPublic: 7).
    let pub_signals = &fixture.pub_signals;
    assert_eq!(
        pub_signals.len(),
        7,
        "expected nPublic=7 for anon_nullifier_transfer"
    );
    let nullifier_0 = BytesN::from_array(&env, &fe_bytes(&pub_signals[0]));
    let nullifier_1 = BytesN::from_array(&env, &fe_bytes(&pub_signals[1]));
    let root = BytesN::from_array(&env, &fe_bytes(&pub_signals[2]));
    let output_0 = BytesN::from_array(&env, &fe_bytes(&pub_signals[5]));
    let output_1 = BytesN::from_array(&env, &fe_bytes(&pub_signals[6]));

    // Seed the two real input-UTXO commitments into the on-chain tree - the only way to seed
    // genesis UTXOs today (no mint/deposit entrypoint yet). Insertion order doesn't affect an
    // SMT's final root.
    env.as_contract(&contract_id, || {
        for leaf in seed_leaves.iter() {
            let idx = U256::from_be_bytes(&env, &Bytes::from_array(&env, &fe_bytes(&leaf.index)));
            let v = U256::from_be_bytes(&env, &Bytes::from_array(&env, &fe_bytes(&leaf.value)));
            tree::insert_leaf(&env, idx, v);
        }
    });

    // Cross-implementation parity check, concretely: Go's `LFDT-Paladin/smt` (which produced
    // this fixture's claimed root) and Rust's `tree.rs` must agree, or the proof - which commits
    // to a specific root - can never be accepted.
    let expected_root = bytes32_to_u256(&env, &root);
    assert_eq!(
        client.get_root(),
        expected_root,
        "tree.rs's root after seeding the real input UTXOs must match the fixture's claimed root"
    );

    let proof = Groth16Proof {
        a: G1Affine::from_bytes(BytesN::from_array(
            &env,
            &g1_bytes(&fixture.proof.pi_a[0], &fixture.proof.pi_a[1]),
        )),
        b: G2Affine::from_bytes(BytesN::from_array(
            &env,
            &g2_bytes(
                &fixture.proof.pi_b[0][0],
                &fixture.proof.pi_b[0][1],
                &fixture.proof.pi_b[1][0],
                &fixture.proof.pi_b[1][1],
            ),
        )),
        c: G1Affine::from_bytes(BytesN::from_array(
            &env,
            &g1_bytes(&fixture.proof.pi_c[0], &fixture.proof.pi_c[1]),
        )),
    };

    // Both nullifiers are real (non-padding) - matches the fixture's enabled=[1,1] signals.
    let nullifiers = soroban_sdk::Vec::from_array(&env, [nullifier_0, nullifier_1]);
    let outputs = soroban_sdk::Vec::from_array(&env, [output_0, output_1]);

    client.transfer(
        &b32(&env, 100),
        &nullifiers,
        &outputs,
        &root,
        &proof,
        &Bytes::new(&env),
    );
}

fn b32(env: &Env, tag: u8) -> BytesN<32> {
    BytesN::from_array(env, &[tag; 32])
}
